name: example
description: A Very Good Example for the Flame Behavior Pattern.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.1.1
  flame_behaviors:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

dependency_overrides:
  flame:
    git: 
      url: https://github.com/flame-engine/flame
      path: packages/flame
