version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/flame_behaviors"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/flame_behaviors/example"
    schedule:
      interval: "daily"
