name: flame_steering_behaviors
description: Flame Steering Behaviors brings steering algorithms to the behavior pattern, built by Very Good Ventures.
version: 0.1.0
homepage: https://github.com/VeryGoodOpenSource/flame_behaviors
repository: https://github.com/VeryGoodOpenSource/flame_behaviors
issue_tracker: https://github.com/VeryGoodOpenSource/flame_behaviors/issues
documentation: https://github.com/VeryGoodOpenSource/flame_behaviors/tree/main/docs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  flame: ">=1.10.0 <2.0.0"
  flame_behaviors: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.13.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ">=5.1.0 <7.0.0"
