name: example
description: A Very Good Example for steering behaviors.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ">=1.10.0 <2.0.0"
  flame_behaviors: ">=1.0.0 <2.0.0"
  flame_steering_behaviors:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.13.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
