name: flame_steering_behaviors

on:
  pull_request:
    paths:
      - ".github/workflows/flame_steering_behaviors.yaml"
      - "packages/flame_steering_behaviors/lib/**"
      - "packages/flame_steering_behaviors/test/**"
      - "packages/flame_steering_behaviors/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/flame_steering_behaviors.yaml"
      - "packages/flame_steering_behaviors/lib/**"
      - "packages/flame_steering_behaviors/test/**"
      - "packages/flame_steering_behaviors/pubspec.yaml"

jobs:
  build:
    strategy:
      matrix:
        flutter-version:
          # The version of Flutter to use should use the minimum Dart SDK version supported by the package,
          # refer to https://docs.flutter.dev/development/tools/sdk/releases.
          - "3.24.0"
          - "3.x"
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/flame_steering_behaviors
      flutter_channel: stable
      flutter_version: ${{ matrix.flutter-version }}

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/flame_steering_behaviors
